server:
  port: 9002
spring:
  application:
    name: FDN-WebTraceStore
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration

webtrace:
  database:
    host: localhost
    port: 27017
    database: WebTrace
    uri:
    password:
    source:
    connectionTimeout: 15000
    autoConnectRetry: true
  collection:
    name: WebTraceStore